language: php

jobs:
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      env:
        - lint=1
        - test_jwt=yes
    - php: '7.4'
      env:
        - deps=low
        - test_jwt=yes
    - php: '8.0'
      env:
        - test_jwt=yes

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $lint = '1' ]]; then wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.16.3/php-cs-fixer.phar; fi
  - if [[ $lint = '1' ]]; then wget https://github.com/phpstan/phpstan/releases/download/0.12.25/phpstan.phar; fi

before_script:
  - phpenv config-rm xdebug.ini

install:
  - if [[ $test_jwt != 'yes' ]]; then
      composer remove --no-update --dev lcobucci/jwt;
    fi

  - if [[ $deps = 'low' ]]; then
      composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi;
    else
      composer update --prefer-dist --no-progress --no-suggest --prefer-stable --ansi;
    fi

script:
  - vendor/bin/simple-phpunit
  - if [[ $lint = '1' ]]; then php php-cs-fixer.phar fix --dry-run --diff --no-ansi; fi
  - if [[ $lint = '1' ]]; then php phpstan.phar analyse; fi
