name: "unit tests"

on: ["pull_request", "push"]

permissions:
  contents: read

jobs:
  unit-tests:
    name: "unit tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v5"
        with:
          persist-credentials: false

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "caching dependencies"
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.operating-system }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.operating-system }}"

      - name: "installing lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest"

      - name: "installing highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "installing PHPUnit"
        run: "php vendor/bin/simple-phpunit install"

      - name: "running unit tests"
        if: ${{ matrix.dependencies == 'highest' }}
        env:
          SYMFONY_DEPRECATIONS_HELPER: 1
        run: "php vendor/bin/simple-phpunit"

      - name: "running unit tests"
        if: ${{ matrix.dependencies == 'lowest' }}
        env:
          SYMFONY_DEPRECATIONS_HELPER: max[self]=0
        run: "php vendor/bin/simple-phpunit"
